name: Lint and Format
on:
 push:
 pull_request:
jobs:
 format:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v2
      with:
        node-version: "18.x"
    - run: npm install
    - run: npm run lint
    - run: npm run prettier
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply linting and formatting changes
        branch: ${{ github.head_ref }}
